### ISSUE TITLE
Cannot create the alignment 

### ISSUE THREAD

**Issue by agnibhat** [dwinter/pafr#21]
Hi, 

I am new to genomic data analysis and I am having trouble generating the alignment. 

`test_alignment <- system.file("extdata", "fungi.paf", package="pafr")`

In this code, what does "extdata" stand for? The code fails to identify the file in the working directory in R studio. As output, I only get an empty table with one row and one column. Really appreciate any suggestions. Thanks!

**Comment by agnibhat** [comment]
Figured it out!

**Comment by dwinter** [comment]
Glad you worked this out @agnibhat , in case anyone runs into this issue, this "extdata" trick is just a way to ensure a user on any system (mac, linux, windows...) can access the example data used in the README and the vignette. Typically, you won't need to use "extdata" or `system.file` to use pafr.
